import AppKit
import Foundation
import Observation

enum AppLanguage: String, Sendable, Codable, CaseIterable, Identifiable {
    case vietnamese = "vi"
    case english = "en"
    case japanese = "ja"
    case chinese = "zh-Hans"

    var id: String { rawValue }

    static func preferred(from identifiers: [String] = Locale.preferredLanguages) -> AppLanguage {
        for identifier in identifiers {
            let value = identifier.lowercased()
            if value.hasPrefix("vi") { return .vietnamese }
            if value.hasPrefix("en") { return .english }
            if value.hasPrefix("ja") { return .japanese }
            if value.hasPrefix("zh") { return .chinese }
        }
        return .english
    }

    var locale: Locale { Locale(identifier: rawValue) }
}

enum L10n {
    private static let values: [AppLanguage: [String: String]] = [
        .vietnamese: [
            "waiting_login": "Đang chờ đăng nhập…",
            "cancel": "Huỷ",
            "loading": "Đang tải…",
            "no_accounts": "Chưa có tài khoản",
            "no_accounts_description": "Thêm mới hoặc import tài khoản Codex hiện tại.",
            "close": "Đóng",
            "settings": "Cài đặt",
            "accounts": "Tài khoản",
            "general": "Chung",
            "about": "Giới thiệu",
            "app_version": "Phiên bản %@",
            "app_description": "Quản lý và chuyển tài khoản Codex, Claude Code, Cursor Agent, Antigravity và GitHub Copilot ngay trên menu bar macOS.",
            "community_disclaimer": "Dự án cộng đồng không chính thức, không liên kết hoặc được OpenAI, Anthropic, Cursor, Google hay GitHub bảo trợ.",
            "manage_accounts": "Quản lý tài khoản",
            "account_count": "%d tài khoản",
            "add_provider": "Thêm dịch vụ",
            "previous_provider": "Dịch vụ trước",
            "next_provider": "Dịch vụ tiếp theo",
            "preview": "Giao diện mẫu",
            "logic_not_connected": "Chưa kết nối logic",
            "codex_cli": "Codex CLI",
            "binary_path": "Đường dẫn Binary",
            "not_configured": "Chưa thiết lập",
            "configure_cli_in_accounts": "Chọn Codex Binary ở phía trên để thêm tài khoản.",
            "app_preferences": "Tuỳ chọn ứng dụng",
            "visible_providers": "Dịch vụ hiển thị",
            "language": "Ngôn ngữ",
            "language_system": "Theo ngôn ngữ hệ thống",
            "language_vietnamese": "Tiếng Việt",
            "language_english": "Tiếng Anh",
            "language_japanese": "Tiếng Nhật",
            "language_chinese": "Tiếng Trung",
            "add_account": "Thêm tài khoản",
            "import_current": "Import tài khoản Codex hiện tại",
            "choose_binary": "Chọn Codex Binary…",
            "launch_at_login": "Mở cùng macOS",
            "quota_reset_notifications": "Thông báo khi hạn mức được đặt lại",
            "quit": "Thoát",
            "active": "Đang sử dụng",
            "switch_account": "Chuyển sang tài khoản này",
            "unknown_email": "Không rõ email",
            "credits": "Credits",
            "credits_accessibility": "Credits: %@",
            "delete_confirmation": "Xoá tài khoản “%@”?",
            "delete_local_profile": "Xoá profile local",
            "delete_message": "Việc này chỉ xoá profile local trên máy Mac. Không xoá tài khoản ChatGPT thật.",
            "delete": "Xoá",
            "quota": "Hạn mức",
            "day": "Ngày",
            "week": "Tuần",
            "month": "Tháng",
            "days": "%d ngày",
            "unlimited": "Không giới hạn",
            "updated": "Cập nhật %@",
            "just_updated": "Vừa cập nhật",
            "refreshing": "Đang cập nhật…",
            "no_quota": "Không lấy được hạn mức",
            "remaining": "Còn lại %d%%",
            "quota_reset_title": "Hạn mức đã được đặt lại",
            "quota_reset_message": "Tài khoản “%@” đã được đặt lại hạn mức %@.",
            "quota_accessibility": "Hạn mức %@: %@",
            "no_reset_time": "Không có thời gian đặt lại",
            "reset_after_hours": "Đặt lại sau %d giờ %d phút",
            "reset_after_minutes": "Đặt lại sau %d phút",
            "reset_in_days": "Đặt lại sau %d ngày %d giờ",
            "reset_on_date": "Đặt lại lúc %@, %@",
            "select_binary_title": "Chọn Codex Binary",
            "invalid_binary": "File đã chọn không phải Codex CLI hợp lệ.",
            "codex_cli_not_found": "Không tìm thấy Codex CLI.",
            "codex_cli_setup_description": "Hãy cài Codex CLI hoặc chọn file thực thi Codex trên máy Mac.",
            "account_exists": "Tài khoản này đã có trong LLM Account Switcher.",
            "preparing_login": "Đang chuẩn bị đăng nhập ChatGPT…",
            "waiting_chatgpt_login": "Đang chờ đăng nhập ChatGPT…",
            "usage_unavailable": "Tạm thời không lấy được hạn mức",
            "workspace_discovery_timed_out": "Kết nối tới Codex đã quá thời gian chờ. Vui lòng thử lại.",
            "codex_session_expired": "Phiên đăng nhập Codex của tài khoản này đã hết hạn. Hãy đăng nhập lại tài khoản.",
            "reauthentication_required_title": "Đăng nhập lại tài khoản?",
            "reauthentication_required_message": "Phiên đăng nhập của “%@” đã hết hạn hoặc không khớp. Đăng nhập lại để tiếp tục chuyển tài khoản.",
            "reauthenticate": "Đăng nhập lại",
            "reauthenticating_account": "Đang đăng nhập lại tài khoản…",
            "reauthenticate_wrong_account": "Bạn đã đăng nhập “%@”, không phải “%@”. Hãy đăng nhập lại đúng tài khoản.",
            "login_url_missing": "Codex CLI không trả về liên kết đăng nhập.",
            "login_response_mismatch": "Phản hồi đăng nhập không khớp.",
            "login_failed": "Đăng nhập không thành công.",
            "login_not_completed": "Không thể hoàn tất đăng nhập. Vui lòng thử lại.",
            "chatgpt_only": "Codex chỉ hỗ trợ tài khoản ChatGPT.",
            "app_server_stopped": "Codex app-server đã dừng.",
            "app_server_no_response": "Codex app-server không phản hồi.",
            "login_timeout": "Hết thời gian chờ đăng nhập.",
            "app_server_exited": "Codex app-server đã thoát.",
            "temp_file_failed": "Không thể tạo file tạm.",
            "target_auth_missing": "Tài khoản đích chưa có thông tin đăng nhập.",
            "external_active_error": "Phát hiện tài khoản Codex khác đang sử dụng. Hãy import hoặc kích hoạt lại tài khoản.",
            "switch_verify_mismatch": "Xác minh tài khoản sau khi chuyển không khớp.",
            "claude_code": "Claude Code",
            "import_current_claude": "Import tài khoản Claude hiện tại",
            "choose_claude_binary": "Chọn Claude Binary…",
            "managed_claude_command": "Lệnh Claude theo tài khoản đã chọn",
            "copy_path": "Sao chép đường dẫn",
            "select_claude_binary_title": "Chọn Claude Binary",
            "invalid_claude_binary": "File đã chọn không phải Claude Code CLI hợp lệ.",
            "claude_cli_not_found": "Không tìm thấy Claude Code CLI.",
            "claude_cli_setup_description": "Hãy cài Claude Code CLI hoặc chọn file thực thi Claude trên máy Mac.",
            "configure_claude_cli_in_accounts": "Chọn Claude Binary ở phía trên để thêm tài khoản.",
            "no_claude_accounts_description": "Thêm mới hoặc import tài khoản Claude hiện tại.",
            "claude_not_logged_in": "Profile Claude này chưa đăng nhập.",
            "claude_status_failed": "Không thể đọc trạng thái đăng nhập Claude.",
            "claude_status_invalid": "Claude CLI trả về trạng thái đăng nhập không hợp lệ.",
            "claude_command_timeout": "Lệnh Claude đã quá thời gian chờ.",
            "waiting_claude_login": "Đang chờ đăng nhập Claude…",
            "delete_claude_message": "Việc này chỉ xoá profile Claude local trên máy Mac, không xoá tài khoản Claude thật.",
            "cursor_agent": "Cursor Agent CLI",
            "import_current_cursor": "Import tài khoản Cursor hiện tại",
            "choose_cursor_binary": "Chọn Cursor Agent Binary…",
            "managed_cursor_command": "Lệnh Cursor theo tài khoản đã chọn",
            "select_cursor_binary_title": "Chọn Cursor Agent Binary",
            "invalid_cursor_binary": "File đã chọn không phải Cursor Agent CLI hợp lệ.",
            "cursor_cli_not_found": "Không tìm thấy Cursor Agent CLI.",
            "cursor_cli_setup_description": "Hãy cài Cursor Agent CLI hoặc chọn file thực thi Agent trên máy Mac.",
            "configure_cursor_cli_in_accounts": "Chọn Cursor Agent Binary ở phía trên để thêm tài khoản.",
            "no_cursor_accounts_description": "Thêm mới hoặc import tài khoản Cursor hiện tại.",
            "cursor_not_logged_in": "Profile Cursor này chưa đăng nhập.",
            "cursor_status_failed": "Không thể đọc trạng thái đăng nhập Cursor.",
            "cursor_command_timeout": "Lệnh Cursor đã quá thời gian chờ.",
            "waiting_cursor_login": "Đang chờ đăng nhập Cursor…",
            "delete_cursor_message": "Việc này chỉ xoá profile Cursor local trên máy Mac, không xoá tài khoản Cursor thật.",
            "antigravity_cli": "Antigravity CLI",
            "import_current_antigravity": "Import tài khoản Antigravity hiện tại",
            "choose_antigravity_binary": "Chọn Antigravity Binary…",
            "select_antigravity_binary_title": "Chọn Antigravity Binary",
            "invalid_antigravity_binary": "File đã chọn không phải Antigravity CLI hợp lệ.",
            "antigravity_cli_not_found": "Không tìm thấy Antigravity CLI.",
            "antigravity_cli_setup_description": "Hãy cài Antigravity CLI hoặc chọn file thực thi agy trên máy Mac.",
            "configure_antigravity_cli_in_accounts": "Chọn Antigravity Binary ở phía trên để thêm tài khoản.",
            "no_antigravity_accounts_description": "Thêm mới hoặc import tài khoản Antigravity hiện tại.",
            "antigravity_not_logged_in": "Antigravity CLI hiện chưa đăng nhập.",
            "antigravity_login_required": "Phiên Antigravity này không còn trong Keychain. Hãy đăng nhập lại tài khoản.",
            "waiting_antigravity_login": "Đang chờ đăng nhập Antigravity trong Terminal…",
            "delete_antigravity_message": "Việc này chỉ xoá phiên Antigravity local khỏi Keychain, không xoá tài khoản Google thật.",
            "antigravity_terminal_failed": "Không thể mở Terminal để đăng nhập Antigravity.",
            "antigravity_keychain_read_failed": "Không thể đọc phiên Antigravity từ Keychain.",
            "antigravity_keychain_write_failed": "Không thể lưu phiên Antigravity vào Keychain.",
            "antigravity_keychain_invalid": "Dữ liệu đăng nhập Antigravity trong Keychain không hợp lệ.",
            "copilot_cli": "GitHub Copilot CLI",
            "managed_copilot_command": "Lệnh Copilot đang quản lý",
            "import_current_copilot": "Import các tài khoản Copilot hiện tại",
            "choose_copilot_binary": "Chọn Copilot Binary…",
            "select_copilot_binary_title": "Chọn Copilot Binary",
            "invalid_copilot_binary": "File đã chọn không phải GitHub Copilot CLI hợp lệ.",
            "copilot_cli_not_found": "Không tìm thấy GitHub Copilot CLI.",
            "copilot_cli_setup_description": "Hãy cài GitHub Copilot CLI hoặc chọn file thực thi copilot trên máy Mac.",
            "configure_copilot_cli_in_accounts": "Chọn Copilot Binary ở phía trên để thêm tài khoản.",
            "no_copilot_accounts_description": "Đăng nhập mới hoặc import các tài khoản Copilot hiện tại.",
            "copilot_not_logged_in": "GitHub Copilot CLI hiện chưa đăng nhập.",
            "copilot_login_required": "Tài khoản Copilot này không còn trong cấu hình CLI. Hãy đăng nhập lại.",
            "copilot_config_invalid": "Cấu hình GitHub Copilot CLI không hợp lệ.",
            "copilot_command_timeout": "Lệnh GitHub Copilot đã quá thời gian chờ.",
            "waiting_copilot_login": "Đang chờ đăng nhập GitHub Copilot…",
            "delete_copilot_message": "Việc này chỉ xoá tài khoản khỏi LLM Account Switcher, không xoá tài khoản GitHub thật.",
            "open_account_settings": "Mở cài đặt tài khoản",
            "enable_provider": "Bật %@",
            "provider_disabled": "%@ đang tắt",
            "provider_disabled_description": "Bật lại dịch vụ này ở phía trên để quản lý tài khoản.",
            "onboarding_title": "Thiết lập lần đầu",
            "onboarding_choose_provider": "Chọn LLM đầu tiên",
            "onboarding_choose_provider_description": "Chọn một dịch vụ để bắt đầu. Có thể thêm các LLM khác trong Cài đặt sau.",
            "onboarding_binary_title": "Kiểm tra đường dẫn",
            "onboarding_binary_description": "LLM Account Switcher tự tìm đường dẫn %@. Có thể thay đổi nếu cần.",
            "onboarding_detecting_binary": "Đang tự động tìm binary…",
            "onboarding_change_path": "Thay đổi…",
            "onboarding_binary_not_found": "Không tự tìm thấy binary. Hãy chọn đường dẫn thủ công.",
            "onboarding_sign_in_title": "Đăng nhập %@",
            "onboarding_sign_in_description": "Đăng nhập tài khoản đầu tiên để hoàn tất thiết lập.",
            "onboarding_back": "Quay lại",
            "onboarding_continue": "Tiếp tục",
            "onboarding_sign_in": "Đăng nhập",
        ],
        .english: [
            "waiting_login": "Waiting for sign-in…",
            "cancel": "Cancel",
            "loading": "Loading…",
            "no_accounts": "No accounts",
            "no_accounts_description": "Add an account or import the current Codex account.",
            "close": "Close",
            "settings": "Settings",
            "accounts": "Accounts",
            "general": "General",
            "about": "About",
            "app_version": "Version %@",
            "app_description": "Manage and switch Codex, Claude Code, Cursor Agent, Antigravity, and GitHub Copilot accounts from the macOS menu bar.",
            "community_disclaimer": "An unofficial community project. Not affiliated with or endorsed by OpenAI, Anthropic, Cursor, Google, or GitHub.",
            "manage_accounts": "Manage Accounts",
            "account_count": "%d accounts",
            "add_provider": "Add provider",
            "previous_provider": "Previous provider",
            "next_provider": "Next provider",
            "preview": "Preview",
            "logic_not_connected": "Logic not connected",
            "codex_cli": "Codex CLI",
            "binary_path": "Binary Path",
            "not_configured": "Not configured",
            "configure_cli_in_accounts": "Choose the Codex Binary above to add an account.",
            "app_preferences": "App Preferences",
            "visible_providers": "Visible Providers",
            "language": "Language",
            "language_system": "System Language",
            "language_vietnamese": "Vietnamese",
            "language_english": "English",
            "language_japanese": "Japanese",
            "language_chinese": "Chinese",
            "add_account": "Add Account",
            "import_current": "Import Current Codex Account",
            "choose_binary": "Choose Codex Binary…",
            "launch_at_login": "Open at Login",
            "quota_reset_notifications": "Notify when usage limits reset",
            "quit": "Quit",
            "active": "Active account",
            "switch_account": "Switch to this account",
            "unknown_email": "Unknown email",
            "credits": "Credits",
            "credits_accessibility": "Credits: %@",
            "delete_confirmation": "Delete account “%@”?",
            "delete_local_profile": "Delete Local Profile",
            "delete_message": "This only removes the local profile from this Mac. It does not delete the ChatGPT account.",
            "delete": "Delete",
            "quota": "Quota",
            "day": "Day",
            "week": "Week",
            "month": "Month",
            "days": "%d days",
            "unlimited": "Unlimited",
            "updated": "Updated %@",
            "just_updated": "Just updated",
            "refreshing": "Updating…",
            "no_quota": "Quota unavailable",
            "remaining": "%d%% left",
            "quota_reset_title": "Usage limit reset",
            "quota_reset_message": "Account “%@” has had its %@ limit reset.",
            "quota_accessibility": "%@ quota: %@",
            "no_reset_time": "Reset time unavailable",
            "reset_after_hours": "Resets in %d hours %d minutes",
            "reset_after_minutes": "Resets in %d minutes",
            "reset_in_days": "Resets in %d days %d hours",
            "reset_on_date": "Resets at %@, %@",
            "select_binary_title": "Choose Codex Binary",
            "invalid_binary": "The selected file is not a valid Codex CLI.",
            "codex_cli_not_found": "Codex CLI was not found.",
            "codex_cli_setup_description": "Install Codex CLI or choose the Codex executable on this Mac.",
            "account_exists": "This account is already in LLM Account Switcher.",
            "preparing_login": "Preparing ChatGPT sign-in…",
            "waiting_chatgpt_login": "Waiting for ChatGPT sign-in…",
            "usage_unavailable": "Usage is temporarily unavailable",
            "workspace_discovery_timed_out": "Connection to Codex timed out. Please try again.",
            "codex_session_expired": "This Codex account session has expired. Please sign in to the account again.",
            "reauthentication_required_title": "Sign in again?",
            "reauthentication_required_message": "The session for “%@” has expired or does not match. Sign in again to continue switching accounts.",
            "reauthenticate": "Sign In Again",
            "reauthenticating_account": "Signing in to the account again…",
            "reauthenticate_wrong_account": "You signed in as “%@”, not “%@”. Please sign in with the correct account.",
            "login_url_missing": "Codex CLI did not return a sign-in link.",
            "login_response_mismatch": "The sign-in response did not match.",
            "login_failed": "Sign-in failed.",
            "login_not_completed": "Sign-in could not be completed. Please try again.",
            "chatgpt_only": "Codex only supports ChatGPT accounts.",
            "app_server_stopped": "Codex app-server stopped.",
            "app_server_no_response": "Codex app-server did not respond.",
            "login_timeout": "The sign-in request timed out.",
            "app_server_exited": "Codex app-server exited.",
            "temp_file_failed": "Could not create a temporary file.",
            "target_auth_missing": "The target account has no sign-in credentials.",
            "external_active_error": "Another Codex account is active. Import it or reactivate the saved account.",
            "switch_verify_mismatch": "Account verification failed after switching.",
            "claude_code": "Claude Code",
            "import_current_claude": "Import Current Claude Account",
            "choose_claude_binary": "Choose Claude Binary…",
            "managed_claude_command": "Claude command for the selected account",
            "copy_path": "Copy Path",
            "select_claude_binary_title": "Choose Claude Binary",
            "invalid_claude_binary": "The selected file is not a valid Claude Code CLI.",
            "claude_cli_not_found": "Claude Code CLI was not found.",
            "claude_cli_setup_description": "Install Claude Code CLI or choose the Claude executable on this Mac.",
            "configure_claude_cli_in_accounts": "Choose the Claude Binary above to add an account.",
            "no_claude_accounts_description": "Add an account or import the current Claude account.",
            "claude_not_logged_in": "This Claude profile is not signed in.",
            "claude_status_failed": "Could not read Claude sign-in status.",
            "claude_status_invalid": "Claude CLI returned an invalid sign-in status.",
            "claude_command_timeout": "The Claude command timed out.",
            "waiting_claude_login": "Waiting for Claude sign-in…",
            "delete_claude_message": "This only removes the local Claude profile from this Mac. It does not delete the Claude account.",
            "cursor_agent": "Cursor Agent CLI",
            "import_current_cursor": "Import Current Cursor Account",
            "choose_cursor_binary": "Choose Cursor Agent Binary…",
            "managed_cursor_command": "Cursor command for the selected account",
            "select_cursor_binary_title": "Choose Cursor Agent Binary",
            "invalid_cursor_binary": "The selected file is not a valid Cursor Agent CLI.",
            "cursor_cli_not_found": "Cursor Agent CLI was not found.",
            "cursor_cli_setup_description": "Install Cursor Agent CLI or choose the Agent executable on this Mac.",
            "configure_cursor_cli_in_accounts": "Choose the Cursor Agent Binary above to add an account.",
            "no_cursor_accounts_description": "Add an account or import the current Cursor account.",
            "cursor_not_logged_in": "This Cursor profile is not signed in.",
            "cursor_status_failed": "Could not read the Cursor sign-in status.",
            "cursor_command_timeout": "The Cursor command timed out.",
            "waiting_cursor_login": "Waiting for Cursor sign-in…",
            "delete_cursor_message": "This only removes the local Cursor profile from this Mac. It does not delete the Cursor account.",
            "antigravity_cli": "Antigravity CLI",
            "import_current_antigravity": "Import Current Antigravity Account",
            "choose_antigravity_binary": "Choose Antigravity Binary…",
            "select_antigravity_binary_title": "Choose Antigravity Binary",
            "invalid_antigravity_binary": "The selected file is not a valid Antigravity CLI.",
            "antigravity_cli_not_found": "Antigravity CLI was not found.",
            "antigravity_cli_setup_description": "Install Antigravity CLI or choose the agy executable on this Mac.",
            "configure_antigravity_cli_in_accounts": "Choose the Antigravity Binary above to add an account.",
            "no_antigravity_accounts_description": "Add an account or import the current Antigravity account.",
            "antigravity_not_logged_in": "Antigravity CLI is not signed in.",
            "antigravity_login_required": "This Antigravity session is no longer in Keychain. Sign in to the account again.",
            "waiting_antigravity_login": "Waiting for Antigravity sign-in in Terminal…",
            "delete_antigravity_message": "This only removes the local Antigravity session from Keychain. It does not delete the Google account.",
            "antigravity_terminal_failed": "Could not open Terminal for Antigravity sign-in.",
            "antigravity_keychain_read_failed": "Could not read the Antigravity session from Keychain.",
            "antigravity_keychain_write_failed": "Could not save the Antigravity session to Keychain.",
            "antigravity_keychain_invalid": "The Antigravity sign-in data in Keychain is invalid.",
            "copilot_cli": "GitHub Copilot CLI",
            "managed_copilot_command": "Managed Copilot Command",
            "import_current_copilot": "Import Current Copilot Accounts",
            "choose_copilot_binary": "Choose Copilot Binary…",
            "select_copilot_binary_title": "Choose Copilot Binary",
            "invalid_copilot_binary": "The selected file is not a valid GitHub Copilot CLI.",
            "copilot_cli_not_found": "GitHub Copilot CLI was not found.",
            "copilot_cli_setup_description": "Install GitHub Copilot CLI or choose the copilot executable on this Mac.",
            "configure_copilot_cli_in_accounts": "Choose the Copilot Binary above to add an account.",
            "no_copilot_accounts_description": "Sign in or import the current Copilot accounts.",
            "copilot_not_logged_in": "GitHub Copilot CLI is not signed in.",
            "copilot_login_required": "This Copilot account is no longer in the CLI configuration. Sign in again.",
            "copilot_config_invalid": "The GitHub Copilot CLI configuration is invalid.",
            "copilot_command_timeout": "The GitHub Copilot command timed out.",
            "waiting_copilot_login": "Waiting for GitHub Copilot sign-in…",
            "delete_copilot_message": "This only removes the account from LLM Account Switcher. It does not delete the GitHub account.",
            "open_account_settings": "Open Account Settings",
            "enable_provider": "Enable %@",
            "provider_disabled": "%@ is turned off",
            "provider_disabled_description": "Turn this provider back on above to manage its accounts.",
            "onboarding_title": "First-time setup",
            "onboarding_choose_provider": "Choose your first LLM",
            "onboarding_choose_provider_description": "Choose one provider to begin. You can add more LLMs later in Settings.",
            "onboarding_binary_title": "Check the binary path",
            "onboarding_binary_description": "LLM Account Switcher automatically finds the %@ path. You can change it if needed.",
            "onboarding_detecting_binary": "Finding the binary automatically…",
            "onboarding_change_path": "Change…",
            "onboarding_binary_not_found": "The binary could not be found automatically. Choose it manually.",
            "onboarding_sign_in_title": "Sign in to %@",
            "onboarding_sign_in_description": "Sign in to your first account to finish setup.",
            "onboarding_back": "Back",
            "onboarding_continue": "Continue",
            "onboarding_sign_in": "Sign In",
        ],
        .japanese: [
            "waiting_login": "サインインを待っています…",
            "cancel": "キャンセル",
            "loading": "読み込み中…",
            "no_accounts": "アカウントがありません",
            "no_accounts_description": "アカウントを追加するか、現在のCodexアカウントを読み込んでください。",
            "close": "閉じる",
            "settings": "設定",
            "accounts": "アカウント",
            "general": "一般",
            "about": "このアプリについて",
            "app_version": "バージョン %@",
            "app_description": "macOSのメニューバーからCodex、Claude Code、Cursor Agent、Antigravity、GitHub Copilotのアカウントを管理・切り替えできます。",
            "community_disclaimer": "OpenAI、Anthropic、Cursor、Google、GitHubとは関係なく、いずれの承認も受けていない非公式のコミュニティプロジェクトです。",
            "manage_accounts": "アカウントを管理",
            "account_count": "%d個のアカウント",
            "add_provider": "サービスを追加",
            "previous_provider": "前のサービス",
            "next_provider": "次のサービス",
            "preview": "プレビュー",
            "logic_not_connected": "ロジック未接続",
            "codex_cli": "Codex CLI",
            "binary_path": "Binaryのパス",
            "not_configured": "未設定",
            "configure_cli_in_accounts": "上でCodex Binaryを選択してアカウントを追加してください。",
            "app_preferences": "アプリの設定",
            "visible_providers": "表示するサービス",
            "language": "言語",
            "language_system": "システムの言語",
            "language_vietnamese": "ベトナム語",
            "language_english": "英語",
            "language_japanese": "日本語",
            "language_chinese": "中国語",
            "add_account": "アカウントを追加",
            "import_current": "現在のCodexアカウントを読み込む",
            "choose_binary": "Codex Binaryを選択…",
            "launch_at_login": "ログイン時に開く",
            "quota_reset_notifications": "使用枠のリセットを通知",
            "quit": "終了",
            "active": "使用中のアカウント",
            "switch_account": "このアカウントに切り替える",
            "unknown_email": "メールアドレス不明",
            "credits": "クレジット",
            "credits_accessibility": "クレジット：%@",
            "delete_confirmation": "アカウント「%@」を削除しますか？",
            "delete_local_profile": "ローカルプロファイルを削除",
            "delete_message": "このMac上のローカルプロファイルのみ削除されます。ChatGPTアカウントは削除されません。",
            "delete": "削除",
            "quota": "使用枠",
            "day": "日",
            "week": "週",
            "month": "月",
            "days": "%d日",
            "unlimited": "無制限",
            "updated": "%@に更新",
            "just_updated": "更新したばかり",
            "refreshing": "更新中…",
            "no_quota": "使用枠を取得できません",
            "remaining": "残り%d%%",
            "quota_reset_title": "使用枠がリセットされました",
            "quota_reset_message": "アカウント「%@」の%@制限がリセットされました。",
            "quota_accessibility": "%@の使用枠：%@",
            "no_reset_time": "リセット時刻がありません",
            "reset_after_hours": "%d時間%d分後にリセット",
            "reset_after_minutes": "%d分後にリセット",
            "reset_in_days": "%d日%d時間後にリセット",
            "reset_on_date": "%2$@の%1$@にリセット",
            "select_binary_title": "Codex Binaryを選択",
            "invalid_binary": "選択したファイルは有効なCodex CLIではありません。",
            "codex_cli_not_found": "Codex CLIが見つかりません。",
            "codex_cli_setup_description": "Codex CLIをインストールするか、このMac上の実行ファイルを選択してください。",
            "account_exists": "このアカウントはすでにLLM Account Switcherにあります。",
            "preparing_login": "ChatGPTへのサインインを準備中…",
            "waiting_chatgpt_login": "ChatGPTへのサインインを待っています…",
            "usage_unavailable": "使用状況を一時的に取得できません",
            "workspace_discovery_timed_out": "Codex への接続がタイムアウトしました。もう一度お試しください。",
            "codex_session_expired": "このCodexアカウントのセッションは期限切れです。もう一度サインインしてください。",
            "reauthentication_required_title": "もう一度サインインしますか？",
            "reauthentication_required_message": "「%@」のセッションが期限切れか、一致していません。アカウントを切り替えるには、もう一度サインインしてください。",
            "reauthenticate": "再度サインイン",
            "reauthenticating_account": "アカウントに再度サインイン中…",
            "reauthenticate_wrong_account": "「%@」としてサインインしましたが、「%@」ではありません。正しいアカウントでサインインしてください。",
            "login_url_missing": "Codex CLIからサインインリンクが返されませんでした。",
            "login_response_mismatch": "サインイン応答が一致しません。",
            "login_failed": "サインインに失敗しました。",
            "login_not_completed": "サインインを完了できませんでした。もう一度お試しください。",
            "chatgpt_only": "CodexはChatGPTアカウントのみ対応しています。",
            "app_server_stopped": "Codex app-serverが停止しました。",
            "app_server_no_response": "Codex app-serverが応答しません。",
            "login_timeout": "サインインの待機時間を超えました。",
            "app_server_exited": "Codex app-serverが終了しました。",
            "temp_file_failed": "一時ファイルを作成できません。",
            "target_auth_missing": "切り替え先アカウントにサインイン情報がありません。",
            "external_active_error": "別のCodexアカウントが使用されています。読み込むか、保存済みアカウントを再度有効にしてください。",
            "switch_verify_mismatch": "切り替え後のアカウント確認に失敗しました。",
            "claude_code": "Claude Code",
            "import_current_claude": "現在のClaudeアカウントを読み込む",
            "choose_claude_binary": "Claude Binaryを選択…",
            "managed_claude_command": "選択したアカウント用のClaudeコマンド",
            "copy_path": "パスをコピー",
            "select_claude_binary_title": "Claude Binaryを選択",
            "invalid_claude_binary": "選択したファイルは有効なClaude Code CLIではありません。",
            "claude_cli_not_found": "Claude Code CLIが見つかりません。",
            "claude_cli_setup_description": "Claude Code CLIをインストールするか、このMac上のClaude実行ファイルを選択してください。",
            "configure_claude_cli_in_accounts": "上でClaude Binaryを選択してアカウントを追加してください。",
            "no_claude_accounts_description": "アカウントを追加するか、現在のClaudeアカウントを読み込んでください。",
            "claude_not_logged_in": "このClaudeプロファイルはサインインしていません。",
            "claude_status_failed": "Claudeのサインイン状態を読み取れませんでした。",
            "claude_status_invalid": "Claude CLIが無効なサインイン状態を返しました。",
            "claude_command_timeout": "Claudeコマンドがタイムアウトしました。",
            "waiting_claude_login": "Claudeへのサインインを待っています…",
            "delete_claude_message": "このMac上のローカルClaudeプロファイルのみ削除されます。Claudeアカウントは削除されません。",
            "cursor_agent": "Cursor Agent CLI",
            "import_current_cursor": "現在のCursorアカウントをインポート",
            "choose_cursor_binary": "Cursor Agent Binaryを選択…",
            "managed_cursor_command": "選択したアカウント用のCursorコマンド",
            "select_cursor_binary_title": "Cursor Agent Binaryを選択",
            "invalid_cursor_binary": "選択したファイルは有効なCursor Agent CLIではありません。",
            "cursor_cli_not_found": "Cursor Agent CLIが見つかりません。",
            "cursor_cli_setup_description": "Cursor Agent CLIをインストールするか、Agent実行ファイルを選択してください。",
            "configure_cursor_cli_in_accounts": "上でCursor Agent Binaryを選択してアカウントを追加してください。",
            "no_cursor_accounts_description": "アカウントを追加するか、現在のCursorアカウントをインポートしてください。",
            "cursor_not_logged_in": "このCursorプロファイルはログインしていません。",
            "cursor_status_failed": "Cursorのログイン状態を取得できませんでした。",
            "cursor_command_timeout": "Cursorコマンドがタイムアウトしました。",
            "waiting_cursor_login": "Cursorへのログインを待っています…",
            "delete_cursor_message": "このMac上のローカルCursorプロファイルのみ削除されます。Cursorアカウントは削除されません。",
            "antigravity_cli": "Antigravity CLI",
            "import_current_antigravity": "現在のAntigravityアカウントを読み込む",
            "choose_antigravity_binary": "Antigravity Binaryを選択…",
            "select_antigravity_binary_title": "Antigravity Binaryを選択",
            "invalid_antigravity_binary": "選択したファイルは有効なAntigravity CLIではありません。",
            "antigravity_cli_not_found": "Antigravity CLIが見つかりません。",
            "antigravity_cli_setup_description": "Antigravity CLIをインストールするか、このMac上のagy実行ファイルを選択してください。",
            "configure_antigravity_cli_in_accounts": "上でAntigravity Binaryを選択してアカウントを追加してください。",
            "no_antigravity_accounts_description": "アカウントを追加するか、現在のAntigravityアカウントを読み込んでください。",
            "antigravity_not_logged_in": "Antigravity CLIにサインインしていません。",
            "antigravity_login_required": "このAntigravityセッションはKeychainにありません。もう一度サインインしてください。",
            "waiting_antigravity_login": "TerminalでAntigravityへのサインインを待っています…",
            "delete_antigravity_message": "Keychain内のローカルAntigravityセッションのみ削除されます。Googleアカウントは削除されません。",
            "antigravity_terminal_failed": "Antigravityへのサインイン用Terminalを開けませんでした。",
            "antigravity_keychain_read_failed": "KeychainからAntigravityセッションを読み取れませんでした。",
            "antigravity_keychain_write_failed": "AntigravityセッションをKeychainに保存できませんでした。",
            "antigravity_keychain_invalid": "Keychain内のAntigravityサインインデータが無効です。",
            "copilot_cli": "GitHub Copilot CLI",
            "managed_copilot_command": "管理対象のCopilotコマンド",
            "import_current_copilot": "現在のCopilotアカウントを読み込む",
            "choose_copilot_binary": "Copilot Binaryを選択…",
            "select_copilot_binary_title": "Copilot Binaryを選択",
            "invalid_copilot_binary": "選択したファイルは有効なGitHub Copilot CLIではありません。",
            "copilot_cli_not_found": "GitHub Copilot CLIが見つかりません。",
            "copilot_cli_setup_description": "GitHub Copilot CLIをインストールするか、このMac上のcopilot実行ファイルを選択してください。",
            "configure_copilot_cli_in_accounts": "上でCopilot Binaryを選択してアカウントを追加してください。",
            "no_copilot_accounts_description": "サインインするか、現在のCopilotアカウントを読み込んでください。",
            "copilot_not_logged_in": "GitHub Copilot CLIにサインインしていません。",
            "copilot_login_required": "このCopilotアカウントはCLI設定にありません。もう一度サインインしてください。",
            "copilot_config_invalid": "GitHub Copilot CLIの設定が無効です。",
            "copilot_command_timeout": "GitHub Copilotコマンドがタイムアウトしました。",
            "waiting_copilot_login": "GitHub Copilotへのサインインを待っています…",
            "delete_copilot_message": "LLM Account Switcherからのみアカウントを削除します。GitHubアカウントは削除されません。",
            "open_account_settings": "アカウント設定を開く",
            "enable_provider": "%@を有効にする",
            "provider_disabled": "%@はオフです",
            "provider_disabled_description": "アカウントを管理するには、上でこのサービスを再度有効にしてください。",
            "onboarding_title": "初回セットアップ",
            "onboarding_choose_provider": "最初のLLMを選択",
            "onboarding_choose_provider_description": "開始するサービスを1つ選択してください。他のLLMは後で設定から追加できます。",
            "onboarding_binary_title": "Binaryのパスを確認",
            "onboarding_binary_description": "LLM Account Switcherが%@のパスを自動検出します。必要に応じて変更できます。",
            "onboarding_detecting_binary": "Binaryを自動検出中…",
            "onboarding_change_path": "変更…",
            "onboarding_binary_not_found": "Binaryを自動検出できませんでした。手動で選択してください。",
            "onboarding_sign_in_title": "%@にサインイン",
            "onboarding_sign_in_description": "最初のアカウントにサインインしてセットアップを完了します。",
            "onboarding_back": "戻る",
            "onboarding_continue": "続ける",
            "onboarding_sign_in": "サインイン",
        ],
        .chinese: [
            "waiting_login": "正在等待登录…",
            "cancel": "取消",
            "loading": "正在加载…",
            "no_accounts": "暂无账号",
            "no_accounts_description": "添加账号或导入当前 Codex 账号。",
            "close": "关闭",
            "settings": "设置",
            "accounts": "账号",
            "general": "通用",
            "about": "关于",
            "app_version": "版本 %@",
            "app_description": "直接从 macOS 菜单栏管理和切换 Codex、Claude Code、Cursor Agent、Antigravity 与 GitHub Copilot 账号。",
            "community_disclaimer": "这是非官方社区项目，与 OpenAI、Anthropic、Cursor、Google 或 GitHub 无隶属关系，也未获得其认可。",
            "manage_accounts": "管理账号",
            "account_count": "%d 个账号",
            "add_provider": "添加服务",
            "previous_provider": "上一个服务",
            "next_provider": "下一个服务",
            "preview": "界面预览",
            "logic_not_connected": "尚未连接逻辑",
            "codex_cli": "Codex CLI",
            "binary_path": "Binary 路径",
            "not_configured": "未配置",
            "configure_cli_in_accounts": "请在上方选择 Codex Binary 后添加账号。",
            "app_preferences": "应用偏好设置",
            "visible_providers": "显示的服务",
            "language": "语言",
            "language_system": "跟随系统语言",
            "language_vietnamese": "越南语",
            "language_english": "英语",
            "language_japanese": "日语",
            "language_chinese": "中文",
            "add_account": "添加账号",
            "import_current": "导入当前 Codex 账号",
            "choose_binary": "选择 Codex Binary…",
            "launch_at_login": "登录时打开",
            "quota_reset_notifications": "额度重置时通知",
            "quit": "退出",
            "active": "当前账号",
            "switch_account": "切换到此账号",
            "unknown_email": "未知邮箱",
            "credits": "积分",
            "credits_accessibility": "积分：%@",
            "delete_confirmation": "删除账号“%@”？",
            "delete_local_profile": "删除本地配置",
            "delete_message": "这只会删除此 Mac 上的本地配置，不会删除 ChatGPT 账号。",
            "delete": "删除",
            "quota": "额度",
            "day": "天",
            "week": "周",
            "month": "月",
            "days": "%d天",
            "unlimited": "无限",
            "updated": "%@更新",
            "just_updated": "刚刚更新",
            "refreshing": "正在更新…",
            "no_quota": "无法获取额度",
            "remaining": "剩余%d%%",
            "quota_reset_title": "额度已重置",
            "quota_reset_message": "账号“%@”的%@额度已重置。",
            "quota_accessibility": "%@额度：%@",
            "no_reset_time": "无重置时间",
            "reset_after_hours": "%d小时%d分钟后重置",
            "reset_after_minutes": "%d分钟后重置",
            "reset_in_days": "%d天%d小时后重置",
            "reset_on_date": "%2$@ %1$@重置",
            "select_binary_title": "选择 Codex Binary",
            "invalid_binary": "所选文件不是有效的 Codex CLI。",
            "codex_cli_not_found": "未找到 Codex CLI。",
            "codex_cli_setup_description": "请安装 Codex CLI，或选择这台 Mac 上的 Codex 可执行文件。",
            "account_exists": "此账号已存在于 LLM Account Switcher 中。",
            "preparing_login": "正在准备登录 ChatGPT…",
            "waiting_chatgpt_login": "正在等待登录 ChatGPT…",
            "usage_unavailable": "暂时无法获取使用额度",
            "workspace_discovery_timed_out": "连接 Codex 超时，请重试。",
            "codex_session_expired": "此 Codex 账号的登录会话已过期。请重新登录该账号。",
            "reauthentication_required_title": "重新登录账号？",
            "reauthentication_required_message": "“%@”的登录会话已过期或不匹配。请重新登录以继续切换账号。",
            "reauthenticate": "重新登录",
            "reauthenticating_account": "正在重新登录账号…",
            "reauthenticate_wrong_account": "您登录的是“%@”，不是“%@”。请使用正确的账号登录。",
            "login_url_missing": "Codex CLI 未返回登录链接。",
            "login_response_mismatch": "登录响应不匹配。",
            "login_failed": "登录失败。",
            "login_not_completed": "无法完成登录。请重试。",
            "chatgpt_only": "Codex 仅支持 ChatGPT 账号。",
            "app_server_stopped": "Codex app-server 已停止。",
            "app_server_no_response": "Codex app-server 无响应。",
            "login_timeout": "等待登录超时。",
            "app_server_exited": "Codex app-server 已退出。",
            "temp_file_failed": "无法创建临时文件。",
            "target_auth_missing": "目标账号没有登录凭据。",
            "external_active_error": "检测到另一个正在使用的 Codex 账号。请导入该账号或重新激活已保存的账号。",
            "switch_verify_mismatch": "切换后账号验证不匹配。",
            "claude_code": "Claude Code",
            "import_current_claude": "导入当前 Claude 账号",
            "choose_claude_binary": "选择 Claude Binary…",
            "managed_claude_command": "使用所选账号的 Claude 命令",
            "copy_path": "复制路径",
            "select_claude_binary_title": "选择 Claude Binary",
            "invalid_claude_binary": "所选文件不是有效的 Claude Code CLI。",
            "claude_cli_not_found": "未找到 Claude Code CLI。",
            "claude_cli_setup_description": "请安装 Claude Code CLI，或选择这台 Mac 上的 Claude 可执行文件。",
            "configure_claude_cli_in_accounts": "请先在上方选择 Claude Binary，然后添加账号。",
            "no_claude_accounts_description": "添加账号或导入当前 Claude 账号。",
            "claude_not_logged_in": "此 Claude 配置尚未登录。",
            "claude_status_failed": "无法读取 Claude 登录状态。",
            "claude_status_invalid": "Claude CLI 返回了无效的登录状态。",
            "claude_command_timeout": "Claude 命令等待超时。",
            "waiting_claude_login": "正在等待 Claude 登录…",
            "delete_claude_message": "这只会删除此 Mac 上的本地 Claude 配置，不会删除真实的 Claude 账号。",
            "cursor_agent": "Cursor Agent CLI",
            "import_current_cursor": "导入当前 Cursor 账号",
            "choose_cursor_binary": "选择 Cursor Agent Binary…",
            "managed_cursor_command": "所选账号使用的 Cursor 命令",
            "select_cursor_binary_title": "选择 Cursor Agent Binary",
            "invalid_cursor_binary": "所选文件不是有效的 Cursor Agent CLI。",
            "cursor_cli_not_found": "未找到 Cursor Agent CLI。",
            "cursor_cli_setup_description": "请安装 Cursor Agent CLI，或选择此 Mac 上的 Agent 可执行文件。",
            "configure_cursor_cli_in_accounts": "请在上方选择 Cursor Agent Binary 后添加账号。",
            "no_cursor_accounts_description": "添加账号或导入当前 Cursor 账号。",
            "cursor_not_logged_in": "此 Cursor 配置尚未登录。",
            "cursor_status_failed": "无法读取 Cursor 登录状态。",
            "cursor_command_timeout": "Cursor 命令已超时。",
            "waiting_cursor_login": "正在等待登录 Cursor…",
            "delete_cursor_message": "这只会删除此 Mac 上的本地 Cursor 配置，不会删除真实的 Cursor 账号。",
            "antigravity_cli": "Antigravity CLI",
            "import_current_antigravity": "导入当前 Antigravity 账号",
            "choose_antigravity_binary": "选择 Antigravity Binary…",
            "select_antigravity_binary_title": "选择 Antigravity Binary",
            "invalid_antigravity_binary": "所选文件不是有效的 Antigravity CLI。",
            "antigravity_cli_not_found": "未找到 Antigravity CLI。",
            "antigravity_cli_setup_description": "请安装 Antigravity CLI，或选择这台 Mac 上的 agy 可执行文件。",
            "configure_antigravity_cli_in_accounts": "请在上方选择 Antigravity Binary 后添加账号。",
            "no_antigravity_accounts_description": "添加账号或导入当前 Antigravity 账号。",
            "antigravity_not_logged_in": "Antigravity CLI 尚未登录。",
            "antigravity_login_required": "Keychain 中已没有此 Antigravity 会话，请重新登录。",
            "waiting_antigravity_login": "正在等待在 Terminal 中登录 Antigravity…",
            "delete_antigravity_message": "这只会从 Keychain 删除本地 Antigravity 会话，不会删除 Google 账号。",
            "antigravity_terminal_failed": "无法打开 Terminal 登录 Antigravity。",
            "antigravity_keychain_read_failed": "无法从 Keychain 读取 Antigravity 会话。",
            "antigravity_keychain_write_failed": "无法将 Antigravity 会话保存到 Keychain。",
            "antigravity_keychain_invalid": "Keychain 中的 Antigravity 登录数据无效。",
            "copilot_cli": "GitHub Copilot CLI",
            "managed_copilot_command": "托管的 Copilot 命令",
            "import_current_copilot": "导入当前 Copilot 账号",
            "choose_copilot_binary": "选择 Copilot Binary…",
            "select_copilot_binary_title": "选择 Copilot Binary",
            "invalid_copilot_binary": "所选文件不是有效的 GitHub Copilot CLI。",
            "copilot_cli_not_found": "未找到 GitHub Copilot CLI。",
            "copilot_cli_setup_description": "请安装 GitHub Copilot CLI，或选择这台 Mac 上的 copilot 可执行文件。",
            "configure_copilot_cli_in_accounts": "请在上方选择 Copilot Binary 后添加账号。",
            "no_copilot_accounts_description": "登录或导入当前 Copilot 账号。",
            "copilot_not_logged_in": "GitHub Copilot CLI 尚未登录。",
            "copilot_login_required": "CLI 配置中已没有此 Copilot 账号，请重新登录。",
            "copilot_config_invalid": "GitHub Copilot CLI 配置无效。",
            "copilot_command_timeout": "GitHub Copilot 命令已超时。",
            "waiting_copilot_login": "正在等待登录 GitHub Copilot…",
            "delete_copilot_message": "这只会从 LLM Account Switcher 删除该账号，不会删除 GitHub 账号。",
            "open_account_settings": "打开账号设置",
            "enable_provider": "启用 %@",
            "provider_disabled": "%@ 已关闭",
            "provider_disabled_description": "请在上方重新启用此服务以管理其账号。",
            "onboarding_title": "首次设置",
            "onboarding_choose_provider": "选择第一个 LLM",
            "onboarding_choose_provider_description": "选择一个服务开始使用。之后可在设置中添加其他 LLM。",
            "onboarding_binary_title": "检查 Binary 路径",
            "onboarding_binary_description": "LLM Account Switcher 会自动查找 %@ 路径，您也可以按需更改。",
            "onboarding_detecting_binary": "正在自动查找 Binary…",
            "onboarding_change_path": "更改…",
            "onboarding_binary_not_found": "无法自动找到 Binary，请手动选择路径。",
            "onboarding_sign_in_title": "登录 %@",
            "onboarding_sign_in_description": "登录第一个账号以完成设置。",
            "onboarding_back": "返回",
            "onboarding_continue": "继续",
            "onboarding_sign_in": "登录",
        ],
    ]

    static func text(_ key: String, language: AppLanguage = .preferred()) -> String {
        values[language]?[key] ?? values[.english]?[key] ?? key
    }

    static func format(_ key: String, language: AppLanguage = .preferred(), arguments: [CVarArg]) -> String {
        String(format: text(key, language: language), locale: language.locale, arguments: arguments)
    }

    static func missingKeys(for language: AppLanguage) -> Set<String> {
        let baseKeys = Set(values[.english, default: [:]].keys)
        let translatedKeys = Set(values[language, default: [:]].keys)
        return baseKeys.subtracting(translatedKeys)
    }
}

@MainActor @Observable
final class LocalizationManager {
    static let shared = LocalizationManager()

    private(set) var language: AppLanguage
    @ObservationIgnored private var languageOverride: AppLanguage?
    @ObservationIgnored private var observers: [NSObjectProtocol] = []

    private init() {
        language = .preferred()
        let center = NotificationCenter.default
        observers.append(center.addObserver(forName: NSLocale.currentLocaleDidChangeNotification, object: nil, queue: .main) { [weak self] _ in
            Task { @MainActor [weak self] in self?.refresh() }
        })
        observers.append(center.addObserver(forName: NSApplication.didBecomeActiveNotification, object: nil, queue: .main) { [weak self] _ in
            Task { @MainActor [weak self] in self?.refresh() }
        })
        observers.append(center.addObserver(forName: UserDefaults.didChangeNotification, object: nil, queue: .main) { [weak self] _ in
            Task { @MainActor [weak self] in self?.refresh() }
        })
        observers.append(DistributedNotificationCenter.default().addObserver(
            forName: Notification.Name("AppleLanguagePreferencesChangedNotification"),
            object: nil,
            queue: .main
        ) { [weak self] _ in
            Task { @MainActor [weak self] in self?.refresh() }
        })
    }

    func text(_ key: String) -> String {
        L10n.text(key, language: language)
    }

    func format(_ key: String, _ arguments: CVarArg...) -> String {
        L10n.format(key, language: language, arguments: arguments)
    }

    func setLanguageOverride(_ language: AppLanguage?) {
        languageOverride = language
        refresh()
    }

    private func refresh() {
        let preferred = languageOverride ?? AppLanguage.preferred()
        if language != preferred { language = preferred }
    }
}
